version: '3.8'
services:

  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_URL: postgres://postgres:123456@localhost:5432/smart-brain-docker
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #     - "6379:6379"

  # Backend
  smart-brain-api:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables"
    container_name: backend
    build: ./
    volumes:
      - ./:/usr/src/smart-brain-api
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    environment:
      POSTGRES_URL: postgres://postgres:123456@localhost:5432/smart-brain-docker
      
      # REDIS_URI: redis://redis:6379
    # Heads up! Docker has updated this feature and now you don't need to define the links property in order for things to work - https://docs.docker.com/compose/networking/
    # links:
    #   - postgres
    #   - redis
