version: '3.8'

services: 
  # Backend API
  smart-brain-api: 
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: smart-brain-docker
      POSTGRES_HOST: postgres
    # links: 
    #   - postgres
    ports: 
      - "3000:3000"
    volumes: 
      - "./:/usr/src/smart-brain-api"
    
  # Postgres Database
  postgres:
    # container_name: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DATABASE: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports: 
      - "5432:5432"